# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'Nishant Kumar'
tagline:          'Nishant Kumar:JavaScript, Angular js, Node.js, Ionic Article'
description:      'Personal Blof for share my thought and technical aspect which I used to do day to day'
url:              http://nishant8bits.github.io
baseurl:          /

author:
  name:           'Nishant Kumar'
  url:            https://twitter.com/mfssharma

paginate:         10

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
